name: todo_app
description: A beautiful application to manage all your To-Do's.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  dynamic_color: ^1.6.6
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  flutter_svg: ^2.0.7
  go_router: ^8.0.5
  google_fonts: ^5.1.0
  shared_preferences: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - google_fonts/
